#!/usr/bin/env node
// tests/prove_journal.mjs — THE prover for the journal's client estate (CLAUDE.md §5; modelled on
// Platform/tests/prove_aiamata.py). One registry of mutations; each is applied to the tree, the NAMED
// tests must FAIL, the file is restored byte-for-byte. Guard rails:
//   - anchor matches exactly once; replacement differs from anchor
//   - pristine tree green first (run_all), unless --skip-pristine
//   - the named test FAILS by name in TAP output, and the suite actually RAN tests (ran 0 = problem)
//   - every discovered suite is named by some mutation; every named suite exists
//   - restoration verified by bytes
// Prints a PROBLEMS block; the gate reads that, never the count. Re-run after ANY edit, comment-only included.
//   node tests/prove_journal.mjs              everything
//   node tests/prove_journal.mjs --only M3    one mutation (substring on id)
//   node tests/prove_journal.mjs --check      registry checks only
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { discover, runFile, ROOT } from './run_all.mjs';

const REGISTRY = [
  { id: 'M1-merge-drops-last', what: 'the merged series loses its last sample -> a resume silently truncates',
    file: 'hr-core.js',
    anchor: "    return Object.keys(byT).map(Number).sort(function (a, b) { return a - b; }).map(function (t) { return byT[t]; });\n",
    replacement: "    return Object.keys(byT).map(Number).sort(function (a, b) { return a - b; }).map(function (t) { return byT[t]; }).slice(0, -1);\n",
    must_fail: ['test_hr_core.mjs:mergeSamples: union by t, ascending, never drops a real sample'] },
  { id: 'M2-est-beats-real', what: 'an estimated sample overwrites a real one -> fabricated data persists (J3)',
    file: 'hr-core.js',
    anchor: "      if (newReal && !curReal) { byT[s.t] = s; return; }\n",
    replacement: "      if (!newReal && curReal) { byT[s.t] = s; return; }\n",
    must_fail: ['test_hr_core.mjs:mergeSamples: a real sample beats an estimated one on either side'] },
  { id: 'M3-tick-off-by-one', what: 'the tick fires one interval late (> instead of >=)',
    file: 'hr-core.js',
    anchor: "    return nowMs - lastOkMs >= iv * 1000;\n",
    replacement: "    return nowMs - lastOkMs > iv * 1000;\n",
    must_fail: ['test_hr_core.mjs:tickDue: due at exactly the interval, not one ms before; first tick always due'] },
  { id: 'M4-stale-boundary', what: 'a session at exactly 6 h reads stale (>= instead of >)',
    file: 'hr-core.js',
    anchor: "      if (nowMs - lastMs > staleS * 1000) {\n",
    replacement: "      if (nowMs - lastMs >= staleS * 1000) {\n",
    must_fail: ['test_hr_core.mjs:resumeDecision: the stale boundary is exactly 6 h from checkpoint_at (± 1 s)'] },
  { id: 'M5-guard-silent', what: 'START allowed over an unfiled local session (the 21 Sep loss)',
    file: 'hr-core.js',
    anchor: "    var src = local || storeOpen;\n    if (!src) return null;\n",
    replacement: "    var src = storeOpen;\n    if (!src) return null;\n",
    must_fail: ['test_hr_core.mjs:startGuard: null with nothing unfiled; a refusal naming minutes and samples otherwise'] },
  { id: 'M6-offline-none', what: 'store unreachable -> "none" even with a local session (an absence reads like a pass)',
    file: 'hr-core.js',
    anchor: "      return local ? { action: localAction, source: 'local', offline: true, local: local }\n",
    replacement: "      return false ? { action: localAction, source: 'local', offline: true, local: local }\n",
    must_fail: ['test_hr_core.mjs:resumeDecision: store unreachable -> the local decision with offline:true, never "none" while a local exists'] },
  { id: 'M7-est-persisted-active', what: 'an est sample is written to the store mid-session',
    file: 'hr-core.js',
    anchor: "    if (session.state === 'active' && samples.some(function (s) { return s.est; })) {\n",
    replacement: "    if (session.state === 'never' && samples.some(function (s) { return s.est; })) {\n",
    must_fail: ['test_hr_core.mjs:checkpointPayload: an est sample in an ACTIVE session is refused (J3); allowed once stopped'] },
  { id: 'M8-state-unchecked', what: 'an unknown state is accepted into the store',
    file: 'hr-core.js',
    anchor: "    if (STATES.indexOf(session.state) < 0) throw new Error('checkpointPayload: unknown state ' + session.state);\n",
    replacement: "    if (STATES.indexOf(session.state) < -1) throw new Error('checkpointPayload: unknown state ' + session.state);\n",
    must_fail: ['test_hr_core.mjs:checkpointPayload: refuses an unknown state and a missing now'] },
  { id: 'M11-engine-merge-not-written', what: 'the engine merges but PATCHes the phone-only series -> the other window\'s samples are lost in the store',
    file: 'hr-core.js',
    anchor: "            body.metadata.samples = merged; body.metadata.rr = rr;\n",
    replacement: "            body.metadata.rr = rr;\n",
    must_fail: ['test_store_session.mjs:G-JA2-3 replay: offline start, dropped tick, second window, stale read, stop, file -> the store holds the union'] },
  { id: 'M12-engine-failed-insert-uncounted', what: 'a failed insert is not counted -> the badge says saving forever (an absence reads like a pass)',
    file: 'hr-core.js',
    anchor: "          if (!ins || ins.error || !ins.data || !ins.data.id) return fail();\n",
    replacement: "          if (!ins || ins.error || !ins.data || !ins.data.id) return false;\n",
    must_fail: ['test_store_session.mjs:G-JA2-3 replay: offline start, dropped tick, second window, stale read, stop, file -> the store holds the union'] },
  { id: 'M13-engine-busy-race', what: 'two writes in flight -> a duplicate record',
    file: 'hr-core.js',
    anchor: "      if (st.busy) return false;\n      st.busy = true;\n",
    replacement: "      st.busy = true;\n",
    must_fail: ['test_store_session.mjs:busy: a second write while one is in flight is refused, not queued into a race'] },
  { id: 'M14-engine-adopt-loses-record', what: 'a resumed session forgets its record id -> a rival record on the first tick',
    file: 'hr-core.js',
    anchor: "    function adopt(pbId, missed) { st.pbId = pbId || null; st.missed = missed || 0; st.lastOk = null; }\n",
    replacement: "    function adopt(pbId, missed) { st.pbId = null; st.missed = missed || 0; st.lastOk = null; }\n",
    must_fail: ['test_store_session.mjs:adopt: a resumed session continues the SAME record and merges what the store already holds'] },
  { id: 'M15-engine-status-hides-missed', what: 'the status line never shows the missed count',
    file: 'hr-core.js',
    anchor: "      if (st.missed > 0) return 'STORE OFFLINE \· ' + st.missed + ' missed';\n",
    replacement: "      if (st.missed > 99) return 'STORE OFFLINE \· ' + st.missed + ' missed';\n",
    must_fail: ['test_store_session.mjs:statusText tells the truth: saving, ok with age, offline with the missed count'] },
  { id: 'M16-reconnect-unbounded', what: 'the reconnect loop never stops (the pre-JA2 behaviour: invisible, endless)',
    file: 'hr-core.js',
    anchor: "    if (attempt >= RECONNECT_MAX) return { retry: false, delayMs: null, attempt: attempt };\n",
    replacement: "    if (attempt >= RECONNECT_MAX * 1000) return { retry: false, delayMs: null, attempt: attempt };\n",
    must_fail: ['test_hr_core.mjs:reconnectPolicy: attempt 0 at once, then every 4 s, stops at RECONNECT_MAX (bounded, A1.3)'] },
  { id: 'M17-visibility-no-reconnect', what: 'returning to the foreground only re-acquires the wake lock (the pre-JA2 handler)',
    file: 'index.html',
    anchor: "  if (!hrChar && hrDevice) { hrReconnectAttempts = 0; hrScheduleReconnect(0); }\n",
    replacement: "  if (!hrChar && hrDevice) { hrReconnectAttempts = 0; }\n",
    must_fail: ['test_shell.mjs:S3 wiring: foreground return reconnects, page hide flushes with keepalive, the loop is bounded by the core'] },
  { id: 'M18-review-shows-discarded', what: 'Log Review lists discarded sessions as if filed (the toggle is decorative)',
    file: 'index.html',
    anchor: "  var data = result.data.filter(function(e) { return rvShowDiscarded || HRCore.stateOf(e) !== 'discarded'; });\n",
    replacement: "  var data = result.data.filter(function(e) { return true || HRCore.stateOf(e) !== 'discarded'; });\n",
    must_fail: ['test_shell.mjs:S4 wiring: Log Review hides discarded behind a toggle, labels states, files and restores without a DELETE'] },
  { id: 'M20-review-toggle-in-footer', what: 'the discarded toggle back in the footer (the state found live on 2026-09-22: under the fixed bar, a tap lands on the bar)',
    file: 'index.html',
    anchor: "    '<div class=\"audit-footer\">&middot; tap any row to expand details</div>';\n",
    replacement: "    '<div class=\"audit-footer\">&middot; tap any row to expand details &middot; <a href=\"#\" onclick=\"rvShowDiscarded=!rvShowDiscarded;render();return false\">show discarded sessions</a></div>';\n",
    must_fail: ['test_shell.mjs:Log Review: the discarded toggle renders ABOVE the list, never in the footer under the fixed bar (found live 2026-09-22)'] },
  { id: 'M19-manifest-truncated', what: 'manifest.json truncated mid-string (the state found live on 2026-09-21) -> Chrome installs a shortcut, not the app',
    file: 'manifest.json',
    anchor: '      "purpose": "maskable"\n    }\n  ]\n}\n',
    replacement: '      "purpose": "',
    must_fail: ["test_shell.mjs:manifest.json parses and meets Chrome's install criteria (found TRUNCATED on 2026-09-21: the shortcut-not-app cause)"] },
  { id: 'M9-sw-shell-drops-core', what: 'the service worker stops caching hr-core.js -> the app shell breaks offline',
    file: 'sw.js',
    anchor: "'/Health-Journal/hr-core.js'",
    replacement: "'/Health-Journal/hr-core.js.missing'",
    must_fail: ['test_shell.mjs:sw.js caches hr-core.js in the shell and the cache version is past v7'] },
  { id: 'M10-html-drops-core', what: 'index.html no longer loads hr-core.js',
    file: 'index.html',
    anchor: '<script src="hr-core.js"></script>',
    replacement: '<script src="hr-core.js.missing"></script>',
    must_fail: ['test_shell.mjs:hr-core.js exists and index.html loads it BEFORE the app script'] },
  { id: 'M21-stale-from-started-at', what: 'staleness measured from started_at although a checkpoint exists -> any session longer than 6 h, or resumed late, reads stale and is never resumed',
    file: 'hr-core.js',
    anchor: "      var lastMs = parseMs(m.checkpoint_at) || parseMs(store.started_at);\n",
    replacement: "      var lastMs = parseMs(store.started_at) || parseMs(m.checkpoint_at);\n",
    must_fail: ['test_hr_core.mjs:resumeDecision: ten-instant clock sweep — stale boundary ± 1 s, both spellings, fallback, checkpoint beats started_at'] },
  // ── W2 S3: native auth (pb-client.js + the index.html wiring) ──
  { id: "W2-C1-header-dropped", what: "the token is never attached -> every call goes out as a guest (reads 200/0 rows once the rules close)",
    file: "pb-client.js",
    anchor: "      if (a) h.Authorization = a.token;\n",
    replacement: "      if (a && false) h.Authorization = a.token;\n",
    must_fail: ["test_pb_client.mjs:every journal verb carries Authorization = the held token", "test_pb_client.mjs:flush: the page-teardown PATCH carries keepalive AND the token, through the same door as every other call"] },
  { id: "W2-C2-no-token-still-sent", what: "a signed-out client still calls the server -> an empty-looking journal after the flip (G-W2-4)",
    file: "pb-client.js",
    anchor: "      if (!usableAuth()) { onAuthLost(",
    replacement: "      if (false) { onAuthLost(",
    must_fail: ["test_pb_client.mjs:no token -> no request: every verb is refused locally with status 401 and the app is told (never an empty-looking journal)"] },
  { id: "W2-C3-expiry-ignored", what: "an expired token is still used -> guest reads that look like an empty journal",
    file: "pb-client.js",
    anchor: "      if (exp === null || exp * 1000 <= now()) {",
    replacement: "      if (exp === null) {",
    must_fail: ["test_pb_client.mjs:an expired token (exp <= now, to the second) is treated as none and cleared; one second earlier it is live"] },
  { id: "W2-C4-expiry-off-by-one", what: "a token at exactly exp reads live (<= became <)",
    file: "pb-client.js",
    anchor: "exp * 1000 <= now()",
    replacement: "exp * 1000 < now()",
    must_fail: ["test_pb_client.mjs:an expired token (exp <= now, to the second) is treated as none and cleared; one second earlier it is live"] },
  { id: "W2-C5-401-keeps-session", what: "a server 401/403 is returned but the dead token is kept -> the app never reaches sign-in",
    file: "pb-client.js",
    anchor: "        if (REFUSED.indexOf(r.status) >= 0) lose('refused');\n",
    replacement: "        if (false) lose('refused');\n",
    must_fail: ["test_pb_client.mjs:a server 401 or 403 on a journal verb ends the session (token cleared, app told); 400 and 404 do not"] },
  { id: "W2-C6-404-signs-out", what: "a rule non-match (404) is read as a lost session -> a bad id signs the user out",
    file: "pb-client.js",
    anchor: "  var REFUSED = [401, 403];",
    replacement: "  var REFUSED = [401, 403, 404];",
    must_fail: ["test_pb_client.mjs:a server 401 or 403 on a journal verb ends the session (token cleared, app told); 400 and 404 do not"] },
  { id: "W2-C7-remove-swallows", what: "a refused DELETE reports success (C-8, the pre-W2 undo)",
    file: "pb-client.js",
    anchor: "undefined, function () { return null; }); return { error: r.error }; },",
    replacement: "undefined, function () { return null; }); return { error: null }; },",
    must_fail: ["test_pb_client.mjs:C-8: remove() returns the refusal, never a silent success"] },
  { id: "W2-C8-empty-body-is-data", what: "a 200 with no readable body becomes an empty list",
    file: "pb-client.js",
    anchor: "      catch (e) { return { data: null, error: { status: r.status, message: 'unreadable response (' + r.status + ')' } }; }\n",
    replacement: "      catch (e) { return { data: [], error: null }; }\n",
    must_fail: ["test_pb_client.mjs:offline and unreadable responses come back as errors, never a throw and never data"] },
  { id: "W2-C9-password-stored", what: "sign-in writes the password into localStorage beside the token",
    file: "pb-client.js",
    anchor: "        writeAuth({ token: r.json.token, id: r.json.record.id, email: r.json.record.email || null });\n        st.reason = null;\n",
    replacement: "        writeAuth({ token: r.json.token, id: r.json.record.id, email: r.json.record.email || null, pw: password });\n        st.reason = null;\n",
    must_fail: ["test_pb_client.mjs:signIn: POSTs identity + password to users/auth-with-password, stores {token,id,email}; the password is stored NOWHERE"] },
  { id: "W2-C10-refresh-signs-out-offline", what: "an offline/5xx refresh clears the token -> a phone in a basement is signed out",
    file: "pb-client.js",
    anchor: "        return { error: { status: r.status, message: 'refresh unavailable (kept signed in)' } };",
    replacement: "        lose('refused'); return { error: { status: r.status, message: 'refresh unavailable (kept signed in)' } };",
    must_fail: ["test_pb_client.mjs:refresh: a refusal (401/403/404) clears the token; offline or a 5xx KEEPS it (a phone in a basement is not signed out)"] },
  { id: "W2-C11-signout-wipes-drafts", what: "sign-out removes the active fast and the capture checkpoint with the token",
    file: "pb-client.js",
    anchor: "      signOut: function () { clearAuth(); st.reason = 'signed out'; },",
    replacement: "      signOut: function () { ['jf', 'hr_session'].forEach(function (k) { storage.removeItem(k); }); clearAuth(); st.reason = 'signed out'; },",
    must_fail: ["test_pb_client.mjs:signOut clears pb_auth and ONLY pb_auth: the active fast, the capture checkpoint and the slots survive"] },
  { id: "W2-C12-flush-no-keepalive", what: "the teardown PATCH loses keepalive -> it dies with the page",
    file: "pb-client.js",
    anchor: "      if (extra && extra.keepalive) init.keepalive = true;",
    replacement: "      if (false) init.keepalive = true;",
    must_fail: ["test_pb_client.mjs:flush: the page-teardown PATCH carries keepalive AND the token, through the same door as every other call"] },
  { id: "W2-C13-exp-not-base64url", what: "the JWT payload is decoded as plain base64 -> a token whose payload carries - or _ reads as unreadable",
    file: "pb-client.js",
    anchor: "parts[1].replace(/-/g, '+').replace(/_/g, '/')",
    replacement: "parts[1]",
    must_fail: ["test_pb_client.mjs:tokenExp reads base64url payloads (the - and _ alphabet, no padding) and refuses anything else"] },
  { id: "W2-C14-untested-verb", what: "a new network verb is added to the client with no test naming it",
    file: "pb-client.js",
    anchor: "      // Page teardown: a keepalive PATCH",
    replacement: "      raw: function (p) { return send('GET', p); },\n      // Page teardown: a keepalive PATCH",
    must_fail: ["test_pb_client.mjs:the verb inventory is derived from the client object itself, both directions (a new verb cannot ship untested)"] },
  { id: "W2-H1-undo-drops-result", what: "undoEntry drops the DELETE result again (C-8 as found)",
    file: "index.html",
    anchor: "    } else r = await PB.remove(id);",
    replacement: "    } else await PB.remove(id);",
    must_fail: ["test_shell.mjs:C-8: every PB journal call site consumes its result (the inventory is derived from the tree, not listed)"] },
  { id: "W2-H2-endfast-clears-on-refusal", what: "a refused END FAST still clears jf -> the fast is lost locally while the store says it is running",
    file: "index.html",
    anchor: "retry'); autoHideErr(6000); return; }\n  }\n  clearActiveFast();",
    replacement: "retry'); autoHideErr(6000); }\n  }\n  clearActiveFast();",
    must_fail: ["test_shell.mjs:C-8: a refused undo and a refused fast-end stay put and say so; the fast stays in jf"] },
  { id: "W2-H3-flush-bypasses-client", what: "the page-hide flush goes back to a raw fetch -> no token, refused once the rules close",
    file: "index.html",
    anchor: "    PB.flush(hrStore.state.pbId, body);   // keepalive: true, with the token (pb-client.js)\n",
    replacement: "    fetch(PB_URL + '/api/collections/journal_entries/records/' + hrStore.state.pbId, { method: 'PATCH', keepalive: true, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });   // keepalive: true\n",
    must_fail: ["test_shell.mjs:W2: the app script issues no request of its own -- its one fetch( is the injection into PBClient.create", "test_shell.mjs:S3 wiring: foreground return reconnects, page hide flushes with keepalive, the loop is bounded by the core"] },
  { id: "W2-H4-authloss-interrupts-capture", what: "a lost session routes to sign-in in the middle of a recording",
    file: "index.html",
    anchor: "  if (hrSessionActive) return;\n  if (location.hash !== '#signin')",
    replacement: "  if (location.hash !== '#signin')",
    must_fail: ["test_shell.mjs:W2: the sign-in gate sits AFTER the capture lock and routes every signed-out view to the sign-in screen"] },
  { id: "W2-H5-no-launch-refresh", what: "the token is never refreshed at launch -> it dies 14 days after sign-in regardless of use",
    file: "index.html",
    anchor: "  PB.refresh();         // W2:",
    replacement: "  void 0;         // W2:",
    must_fail: ["test_shell.mjs:W2: the sign-in gate sits AFTER the capture lock and routes every signed-out view to the sign-in screen"] },
  { id: "W2-H6-review-error-as-empty", what: "Log Review shows a refused read as \"no entries found\" (an absence reads like a pass)",
    file: "index.html",
    anchor: "'<div class=\"empty-state\">could not load entries &middot; '",
    replacement: "'<div class=\"empty-state\">no entries found &middot; '",
    must_fail: ["test_shell.mjs:W2: Log Review never shows a failed read as an empty journal"] },
  { id: "W2-H7-signin-stores-password", what: "the sign-in form copies the password into localStorage",
    file: "index.html",
    anchor: "  pw.value = '';                // the password lives only in the request\n",
    replacement: "  localStorage.setItem('pb_pw', pw.value); pw.value = '';\n",
    must_fail: ["test_shell.mjs:W2: the sign-in screen -- password field, no sign-up, the password cleared after the call and never stored"] },
  { id: "W2-H8-signout-clears-storage", what: "the sign-out link clears all of localStorage (fast, checkpoint, slots)",
    file: "index.html",
    anchor: "  PB.signOut();\n  navigate('#signin');",
    replacement: "  PB.signOut(); localStorage.clear();\n  navigate('#signin');",
    must_fail: ["test_shell.mjs:Q8: the home footer carries a sign-out link, and sign-out clears the token only (drafts survive)"] },
  { id: "W2-H9-sw-drops-client", what: "the service worker stops caching pb-client.js -> the shell cannot boot offline",
    file: "sw.js",
    anchor: "'/Health-Journal/pb-client.js', ",
    replacement: "",
    must_fail: ["test_shell.mjs:W2: pb-client.js exists, loads after hr-core.js and before the app script, and the service worker caches it"] },
  { id: "S20-navigate-same-hash-stale", what: "navigate only sets the hash -> an unchanged hash fires no hashchange and the screen goes stale (END FAST on home, found on the phone s20)",
    file: "index.html",
    anchor: "  if (location.hash === hash) render(); else location.hash = hash;\n",
    replacement: "  location.hash = hash;\n",
    must_fail: ["test_shell.mjs:navigate re-renders when the hash is unchanged (s20: END FAST on home left the banner up until a reload)"] },
  // ── W3b S3: the Lift core (lift-core.js) and hr-core.js's one key (W3b_Build_Brief_v1.md §2.2, gate record) ──
  { id: 'W3b-L1-volume-drops-load', what: 'volume sums reps alone -> every session volume is wrong by the load',
    file: 'lift-core.js',
    anchor: '  function setVolume(s) { return s.r * s.w; }',
    replacement: '  function setVolume(s) { return s.r; }',
    must_fail: ['test_lift_core.mjs:L1: volume = R x W of the TOTAL load, no multiplier (a dumbbell pair is entered summed)'] },
  { id: 'W3b-L2-bodyweight-as-skipped', what: 'R > 0 W 0 is called skipped -> a bodyweight set reads as a skip',
    file: 'lift-core.js',
    anchor: "    if (w === 0) return 'bodyweight';\n",
    replacement: "    if (w === 0) return 'skipped';\n",
    must_fail: ['test_lift_core.mjs:L2: set kinds exactly as the sets view: 0/0 skipped, W 0 bodyweight (done), else loaded'] },
  { id: 'W3b-L2-bodyweight-not-done', what: 'a W 0 set counts as skipped in the status -> a pull-up session reads skipped',
    file: 'lift-core.js',
    anchor: '  function isSkip(s) { return s.r === 0 && s.w === 0; }',
    replacement: '  function isSkip(s) { return s.w === 0; }',
    must_fail: ['test_lift_core.mjs:L2: a bodyweight set counts as DONE in the status (a session of pull-ups is completed, not skipped)'] },
  { id: 'W3b-L3-unconfirmed-files-numbers', what: 'an unconfirmed suggestion files with its suggested numbers -> Kito reads sets that were never done',
    file: 'lift-core.js',
    anchor: '    if (s.c === false) return { r: 0, w: 0 };\n',
    replacement: '    if (s.c === false && false) return { r: 0, w: 0 };\n',
    must_fail: ['test_lift_core.mjs:L3: an unconfirmed set files as R 0 / W 0 and no c, from or prior reaches the filed record'] },
  { id: 'W3b-L3-prior-leaks', what: 'the filed record keeps the active-only `prior` key',
    file: 'lift-core.js',
    anchor: '      return { name: e.name, side: e.side, added: !!e.added, sets: (e.sets || []).map(filedSet) };\n',
    replacement: '      return { name: e.name, side: e.side, added: !!e.added, prior: e.prior, sets: (e.sets || []).map(filedSet) };\n',
    must_fail: ['test_lift_core.mjs:L3: an unconfirmed set files as R 0 / W 0 and no c, from or prior reaches the filed record'] },
  { id: 'W3b-L4-session-references-template', what: 'the session holds the template\'s own lines -> editing the template rewrites a running (and a filed) session',
    file: 'lift-core.js',
    anchor: "      review: '',\n    };\n",
    replacement: "      review: '', lines: m.lines,\n    };\n",
    must_fail: ['test_lift_core.mjs:L4: a session COPIES its template (name + lines) at START; editing, renaming or archiving the template never rewrites it'] },
  { id: 'W3b-L4-archived-template-starts', what: 'an archived template can still start a session (Q1: it left the picker)',
    file: 'lift-core.js',
    anchor: "    if (m.archived) throw new Error('startSession: the template is archived');\n",
    replacement: '',
    must_fail: ['test_lift_core.mjs:L4: a session COPIES its template (name + lines) at START; editing, renaming or archiving the template never rewrites it'] },
  { id: 'W3b-L5-reads-unfiled', what: 'pre-fill reads active and discarded sessions -> a discarded mistake becomes next week\'s suggestion',
    file: 'lift-core.js',
    anchor: "      return r.entry_type === ENTRY_TYPE && m && m.state === 'filed' && m.template && m.template.id === templateId &&\n",
    replacement: "      return r.entry_type === ENTRY_TYPE && m && m.template && m.template.id === templateId &&\n",
    must_fail: ['test_lift_core.mjs:L5: pre-fill reads FILED sessions of the SAME template id, newest first; discarded, active, other templates and other types never'] },
  { id: 'W3b-L5-any-template', what: 'pre-fill ignores the template id -> another workout\'s sets are suggested',
    file: 'lift-core.js',
    anchor: 'm.template.id === templateId &&\n',
    replacement: '(m.template.id === templateId || true) &&\n',
    must_fail: ['test_lift_core.mjs:L5: pre-fill reads FILED sessions of the SAME template id, newest first; discarded, active, other templates and other types never'] },
  { id: 'W3b-L5-oldest-first', what: 'history sorted oldest first -> pre-fill suggests the oldest session',
    file: 'lift-core.js',
    anchor: '    }).sort(function (a, b) { return b.started_ms - a.started_ms; });\n',
    replacement: '    }).sort(function (a, b) { return a.started_ms - b.started_ms; });\n',
    must_fail: ['test_lift_core.mjs:L5: pre-fill reads FILED sessions of the SAME template id, newest first; discarded, active, other templates and other types never'] },
  { id: 'W3b-L6-skips-shrink-count', what: 'the set count ignores skipped rows -> one short day shrinks the next session\'s lines (D-60)',
    file: 'lift-core.js',
    anchor: '    var n = lineOf(history[holding], line).sets.length;\n',
    replacement: '    var n = lineOf(history[holding], line).sets.filter(function (s) { return !isSkip(s); }).length;\n',
    must_fail: ['test_lift_core.mjs:L6: the set COUNT is the most recent session holding the line: a skip never shrinks it, an older longer session never grows it'] },
  { id: 'W3b-L7-skip-prefills-zero', what: 'a skipped set is suggested as 0 x 0 instead of the last time it was done (D-60 (1))',
    file: 'lift-core.js',
    anchor: "        if (s && Number.isInteger(s.r) && typeof s.w === 'number' && !isSkip(s)) {\n",
    replacement: "        if (s && Number.isInteger(s.r) && typeof s.w === 'number') {\n",
    must_fail: ['test_lift_core.mjs:L7: a set never done in any session starts EMPTY (never a 0 x 0 suggestion); a bodyweight set is a done set',
                'test_lift_core.mjs:L6-L8: the Legs Heavy pre-fill: counts from 24 Feb, each set from the last session it was done, older sets dated'] },
  { id: 'W3b-L8-older-set-undated', what: 'a set taken from an older session carries no date -> it reads as last session\'s',
    file: 'lift-core.js',
    anchor: '          if (j !== holding) set.from = history[j].date;\n',
    replacement: '          if (false) set.from = history[j].date;\n',
    must_fail: ['test_lift_core.mjs:L8: `from` only on a set taken from an older session than the one holding the line; a session with no valid offset dates it null, never UTC'] },
  { id: 'W3b-L9-uni-r-before-l', what: 'a unilateral lift adds R before L',
    file: 'lift-core.js',
    anchor: "    if (lateral === 'uni') return [{ name: n, side: 'L' }, { name: n, side: 'R' }];\n",
    replacement: "    if (lateral === 'uni') return [{ name: n, side: 'R' }, { name: n, side: 'L' }];\n",
    must_fail: ['test_lift_core.mjs:L9: a unilateral lift is two lines, L then R, each with its own sets and its side stored'] },
  { id: 'W3b-L10-empty-tick-confirms', what: 'a tick on an empty set confirms it as 0 / 0 -> a skip nobody chose',
    file: 'lift-core.js',
    anchor: "    if (r.value === null && w.value === null) { s.r = null; s.w = null; return { meta: m, refused: null, focus: 'r' }; }\n",
    replacement: '',
    must_fail: ['test_lift_core.mjs:L10: tick on an EMPTY set puts the cursor in R and confirms nothing'] },
  { id: 'W3b-L10-edit-does-not-confirm', what: 'changing a number leaves the set unconfirmed -> an edited set files as a skip',
    file: 'lift-core.js',
    anchor: '    s.c = true;\n    return { meta: m, refused: null, focus: null };\n  }\n  // + SET',
    replacement: '    s.c = false;\n    return { meta: m, refused: null, focus: null };\n  }\n  // + SET',
    must_fail: ['test_lift_core.mjs:L10: changing a number confirms that set (once it carries both numbers)'] },
  { id: 'W3b-L10-first-session-no-sets', what: 'a template\'s first session starts with no sets -> nothing to log into',
    file: 'lift-core.js',
    anchor: 'sets: p ? p.sets : [emptySet()] };\n',
    replacement: 'sets: p ? p.sets : [] };\n',
    must_fail: ['test_lift_core.mjs:L5: no signal = no history = no pre-fill, and logging still works (one empty set per line)'] },
  { id: 'W3b-L10-added-not-flagged', what: 'an exercise added on the day is not marked added -> Kito cannot tell it from the template',
    file: 'lift-core.js',
    anchor: 'added: true, prior: null, sets: [emptySet()] });\n',
    replacement: 'added: false, prior: null, sets: [emptySet()] });\n',
    must_fail: ['test_lift_core.mjs:L10: an exercise added on the day is `added`, starts with one empty set, and never changes the template'] },
  { id: 'W3b-I8-cleared-stays-confirmed', what: 'clearing a number leaves the set confirmed -> it files numbers the user took back',
    file: 'lift-core.js',
    anchor: '    if (s.r === null || s.w === null) { s.c = false; return { meta: m, refused: null, focus: null }; }\n',
    replacement: '    if (s.r === null || s.w === null) { return { meta: m, refused: null, focus: null }; }\n',
    must_fail: ['test_lift_core.mjs:L10 / I-8: clearing a number un-confirms the set, so nothing files that was not confirmed as it stands'] },
  { id: 'W3b-I5-tick-path', what: 'a tick confirms R 0 with a weight (the typo JB ruled blocked, s29)',
    file: 'lift-core.js',
    anchor: "    if (R === 0 && W > 0) { s.r = r.value; s.w = w.value; return { meta: m, refused: ZERO_REPS_WITH_WEIGHT, focus: 'r' }; }\n",
    replacement: '',
    must_fail: ['test_lift_core.mjs:I-5 tick path: R 0 (or empty) with a weight is refused in words and stays unconfirmed'] },
  { id: 'W3b-I5-edit-path', what: 'an edit confirms R 0 with a weight (I-5, the second path)',
    file: 'lift-core.js',
    anchor: "    if (s.r === 0 && s.w > 0) { s.c = false; return { meta: m, refused: ZERO_REPS_WITH_WEIGHT, focus: 'r' }; }\n",
    replacement: '',
    must_fail: ['test_lift_core.mjs:I-5 edit path: an edit that leaves R 0 with a weight is refused and UN-confirms a confirmed set'] },
  { id: 'W3b-input-comma-refused', what: 'a pt-BR decimal comma (22,5) is refused',
    file: 'lift-core.js',
    anchor: ".trim().replace(',', '.');",
    replacement: '.trim();',
    must_fail: ['test_lift_core.mjs:input: reps a whole number, weight a number of kg (a pt-BR comma accepted); anything else refused in words, never a silent 0'] },
  { id: 'W3b-input-silent-zero', what: 'unreadable reps become a silent 0 (the mock\'s Number(x) || 0)',
    file: 'lift-core.js',
    anchor: "    if (!/^\\d+$/.test(s)) return { value: null, error: 'Reps must be a whole number (' + s + ')' };\n",
    replacement: "    if (!/^\\d+$/.test(s)) return { value: 0, error: null };\n",
    must_fail: ['test_lift_core.mjs:input: reps a whole number, weight a number of kg (a pt-BR comma accepted); anything else refused in words, never a silent 0'] },
  { id: 'W3b-L11-status-inverted', what: 'status swaps completed and partial (the view mutation W3b-S1-status-inverted, core side)',
    file: 'lift-core.js',
    anchor: "    return skipped === 0 ? 'completed' : 'partial';\n",
    replacement: "    return skipped === 0 ? 'partial' : 'completed';\n",
    must_fail: ['test_lift_core.mjs:L11: status derived: every set skipped = skipped, some = partial, none = completed; I-1 no sets = skipped'] },
  { id: 'W3b-I1-empty-completed', what: 'a session with no sets reads completed -> the core and the view disagree (I-1)',
    file: 'lift-core.js',
    anchor: "    if (skipped === sets.length) return 'skipped';\n",
    replacement: "    if (sets.length && skipped === sets.length) return 'skipped';\n",
    must_fail: ['test_lift_core.mjs:L11: status derived: every set skipped = skipped, some = partial, none = completed; I-1 no sets = skipped'] },
  { id: 'W3b-L12-range-dropped', what: 'the offset test stops checking |offset| <= 14 h (C-1)',
    file: 'lift-core.js',
    anchor: "    return typeof v === 'number' && Number.isInteger(v) && v % OFFSET_STEP_S === 0 && Math.abs(v) <= MAX_OFFSET_S;\n",
    replacement: "    return typeof v === 'number' && Number.isInteger(v) && v % OFFSET_STEP_S === 0;\n",
    must_fail: ['test_lift_core.mjs:L12 / C-1: no valid offset gives NO date (never the UTC date): a float, a 600, beyond +/-14 h, the -1 sentinel, missing'] },
  { id: 'W3b-L12-step-dropped', what: 'the offset test stops checking the 15-minute step -> the -1 sentinel mints a date',
    file: 'lift-core.js',
    anchor: "    return typeof v === 'number' && Number.isInteger(v) && v % OFFSET_STEP_S === 0 && Math.abs(v) <= MAX_OFFSET_S;\n",
    replacement: "    return typeof v === 'number' && Number.isInteger(v) && Math.abs(v) <= MAX_OFFSET_S;\n",
    must_fail: ['test_lift_core.mjs:L12 / C-1: no valid offset gives NO date (never the UTC date): a float, a 600, beyond +/-14 h, the -1 sentinel, missing'] },
  { id: 'W3b-L12-utc-passed-off', what: 'no valid offset -> the UTC date is passed off as local (the failure L12 names)',
    file: 'lift-core.js',
    anchor: "!Number.isFinite(startedMs) || !isOffset(offsetS)) return null;\n",
    replacement: "!Number.isFinite(startedMs)) return null;\n    if (!isOffset(offsetS)) return iso(startedMs).slice(0, 10);\n",
    must_fail: ['test_lift_core.mjs:L12 / C-1: no valid offset gives NO date (never the UTC date): a float, a 600, beyond +/-14 h, the -1 sentinel, missing'] },
  { id: 'W3b-L12-sign', what: 'the offset is subtracted -> every date on the wrong side of midnight',
    file: 'lift-core.js',
    anchor: '    return iso(startedMs + offsetS * 1000).slice(0, 10);\n',
    replacement: '    return iso(startedMs - offsetS * 1000).slice(0, 10);\n',
    must_fail: ['test_lift_core.mjs:L12: session_date is the local date of started_at at the session offset, both sides of midnight',
                'test_lift_core.mjs:L12: ten-instant sweep, five offsets, against Intl (ICU) as the independent reference'] },
  { id: 'W3b-L14-notes-in-patch', what: 'a Lift PATCH writes notes -> the journal notes Kito must never see gain a Lift path (D-58)',
    file: 'lift-core.js',
    anchor: '          var upd = await pb.update(st.pbId, body);\n',
    replacement: "          var upd = await pb.update(st.pbId, Object.assign({ notes: '' }, body));\n",
    must_fail: ['test_lift_core.mjs:L14: notes is null at the insert and absent from every PATCH; the review lives in metadata.review'] },
  { id: 'W3b-L14-review-to-notes', what: 'the insert copies the review into notes',
    file: 'lift-core.js',
    anchor: 'ended_at: null, notes: null }, body));\n',
    replacement: 'ended_at: null, notes: s.meta.review || null }, body));\n',
    must_fail: ['test_lift_core.mjs:L14: notes is null at the insert and absent from every PATCH; the review lives in metadata.review'] },
  { id: 'W3b-L15-repointed', what: 'a stored HR id is overwritten by a later one -> the link becomes a guess',
    file: 'lift-core.js',
    anchor: '    if (meta.hr_session_id) return { meta: meta, changed: false, conflict: true };\n',
    replacement: '',
    must_fail: ['test_lift_core.mjs:L15 (strap): the HR record id is stored once it exists and never re-pointed; link and none are untouched'] },
  { id: 'W3b-L15-hr-core-drops-key', what: 'hr-core.js stops passing lift_session_id -> the offline-throughout link cannot resolve (Q3 (c))',
    file: 'hr-core.js',
    anchor: '      out.lift_session_id = session.lift_session_id;\n',
    replacement: '      void 0;\n',
    must_fail: ['test_hr_core.mjs:checkpointPayload: lift_session_id passes through when the session carries it, and is ABSENT otherwise (W3b Q3 (c))',
                'test_lift_core.mjs:L15: the HR session names its Lift session through the REAL HR engine, so the offline-throughout link resolves from the HR side'] },
  { id: 'W3b-L15-hr-core-always-key', what: 'every HR session gains a lift_session_id key (null) -> JA2\'s metadata moves for sessions Lift never touched',
    file: 'hr-core.js',
    anchor: '    if (session.lift_session_id !== undefined && session.lift_session_id !== null) {\n',
    replacement: '    out.lift_session_id = session.lift_session_id || null;\n    if (session.lift_session_id !== undefined && session.lift_session_id !== null) {\n',
    must_fail: ['test_hr_core.mjs:checkpointPayload: lift_session_id passes through when the session carries it, and is ABSENT otherwise (W3b Q3 (c))'] },
  { id: 'W3b-L17-unconnected-starts', what: 'START is allowed with the strap chosen but not connected (D-60 (2))',
    file: 'lift-core.js',
    anchor: "    if (opts.hrMode === 'strap' && opts.strapConnected !== true) return { ok: false, reason: 'Connect the strap first' };\n",
    replacement: '',
    must_fail: ['test_lift_core.mjs:L17: with the strap chosen START is refused until it is connected; the HR type is Weightlifting, not asked'] },
  { id: 'W3b-L17-type-drift', what: 'the fixed HR type drifts from the HR screen\'s own list -> a strap session of a type no screen knows',
    file: 'lift-core.js',
    anchor: "  var HR_EXERCISE_TYPE = 'Weightlifting';",
    replacement: "  var HR_EXERCISE_TYPE = 'Resistance';",
    must_fail: ['test_shell.mjs:L17: the HR type Lift fixes is one the HR screen offers (the named type EXISTS in index.html)',
                'test_lift_core.mjs:L17: with the strap chosen START is refused until it is connected; the HR type is Weightlifting, not asked'] },
  { id: 'W3b-L18-failure-uncounted', what: 'a failed insert is not counted -> the strip says saving forever (an absence reads like a pass)',
    file: 'lift-core.js',
    anchor: '          if (!ins || ins.error || !ins.data || !ins.data.id) return fail();\n',
    replacement: '          if (!ins || ins.error || !ins.data || !ins.data.id) return false;\n',
    must_fail: ['test_lift_core.mjs:L18: a failed write is COUNTED and said, never thrown or swallowed; the next success clears it'] },
  { id: 'W3b-L18-filed-bypasses-shape', what: 'a filed write does not go through the file shape -> c reaches the store (or the filing fails)',
    file: 'lift-core.js',
    anchor: "    var out = state === 'filed' ? fileShape(meta) : copy(meta);\n",
    replacement: '    var out = copy(meta);\n',
    must_fail: ['test_lift_core.mjs:L18: in the store from START (insert active), PATCHed whole as sets change, finished filed through the file shape; nothing DELETEs',
                'test_lift_core.mjs:checkpointPayload: refuses an unknown state and a missing now; a filed payload is ALWAYS the file shape'] },
  { id: 'W3b-L18-retry-storm', what: 'due() measures from the last SUCCESS -> offline, every tick retries at once',
    file: 'lift-core.js',
    anchor: '    function due() { return dirty() && HR.tickDue(st.lastTry, now(), CHECKPOINT_SEC); }\n',
    replacement: '    function due() { return dirty() && HR.tickDue(st.lastOk, now(), CHECKPOINT_SEC); }\n',
    must_fail: ['test_lift_core.mjs:L18: touch marks a change; due = unwritten change and >= 5 s since the last attempt; a change during a write stays due'] },
  { id: 'W3b-L18-change-lost-in-flight', what: 'a change made while a write is in flight is marked written -> it never reaches the store',
    file: 'lift-core.js',
    anchor: '        st.lastOk = now(); st.missed = 0; st.writes++; st.written = rev;\n',
    replacement: '        st.lastOk = now(); st.missed = 0; st.writes++; st.written = st.rev;\n',
    must_fail: ['test_lift_core.mjs:L18: touch marks a change; due = unwritten change and >= 5 s since the last attempt; a change during a write stays due'] },
  { id: 'W3b-L18-busy-race', what: 'two writes in flight -> a duplicate session record',
    file: 'lift-core.js',
    anchor: '      if (st.busy) return false;\n      st.busy = true;\n      var rev = st.rev;\n',
    replacement: '      st.busy = true;\n      var rev = st.rev;\n',
    must_fail: ['test_lift_core.mjs:L18: busy: a second write while one is in flight is refused; adopt continues the SAME record'] },
  { id: 'W3b-L18-adopt-forgets', what: 'a resumed session forgets its record id -> a rival record on the first write',
    file: 'lift-core.js',
    anchor: '    function adopt(pbId, missed) { st.pbId = pbId || null;',
    replacement: '    function adopt(pbId, missed) { st.pbId = null;',
    must_fail: ['test_lift_core.mjs:L18: busy: a second write while one is in flight is refused; adopt continues the SAME record'] },
  { id: 'W3b-L18-clock-default', what: 'the engine falls back to its own clock -> time is no longer an input (and the core is no longer pure)',
    file: 'lift-core.js',
    anchor: "    if (typeof now !== 'function') throw new Error('createLiftStoreSession: opts.now is required (time is an input)');\n",
    replacement: "    if (typeof now !== 'function') now = function () { return Date.now(); };\n",
    must_fail: ['test_shell.mjs:lift-core.js exists and is a pure core: no DOM, storage, network, clock, randomness, timer or delete of its own',
                'test_lift_core.mjs:L18: busy: a second write while one is in flight is refused; adopt continues the SAME record'] },
  { id: 'W3b-L19-lock-admits-home', what: 'the Lift lock admits Home -> a stray tap leaves a running session',
    file: 'lift-core.js',
    anchor: '    var allowed = lock.strap ? [LIFT_ROUTE, HR_ROUTE] : [LIFT_ROUTE];\n',
    replacement: "    var allowed = lock.strap ? [LIFT_ROUTE, HR_ROUTE, '#home'] : [LIFT_ROUTE];\n",
    must_fail: ['test_lift_core.mjs:L19: while a Lift session runs every route returns to the Lift screen; with the strap the HR view is admitted too, and only it'] },
  { id: 'W3b-L19-no-lock-without-strap', what: 'a Lift session without the strap is not locked (the mock locks it, I-7)',
    file: 'lift-core.js',
    anchor: '    if (!lock || !lock.lift) return null;\n',
    replacement: '    if (!lock || !lock.lift || !lock.strap) return null;\n',
    must_fail: ['test_lift_core.mjs:L19: while a Lift session runs every route returns to the Lift screen; with the strap the HR view is admitted too, and only it'] },
  { id: 'W3b-L20-hr-blocks-lift', what: 'FINISH files the HR session first and holds the Lift session on its failure (Q3 (a), which JB rejected)',
    file: 'lift-core.js',
    anchor: "    try { liftOk = (await fileLift()) === true; } catch (e) { liftOk = false; }\n    if (typeof fileHr === 'function') {\n      try { hrOk = (await fileHr()) === true; } catch (e) { hrOk = false; }\n    }\n",
    replacement: "    if (typeof fileHr === 'function') {\n      try { hrOk = (await fileHr()) === true; } catch (e) { hrOk = false; }\n    }\n    if (hrOk !== false) { try { liftOk = (await fileLift()) === true; } catch (e) { liftOk = false; } }\n",
    must_fail: ['test_lift_core.mjs:L20: an HR store that REFUSES never blocks the Lift filing; the HR session is kept unfiled with its data'] },
  { id: 'W3b-L20-claims-filed', what: 'the FINISH words say filed when the Lift write failed',
    file: 'lift-core.js',
    anchor: "    var parts = [liftOk ? 'Lift filed' : 'Lift NOT filed: kept, retrying'];\n",
    replacement: "    var parts = ['Lift filed'];\n",
    must_fail: ['test_lift_core.mjs:L20: the four FINISH outcomes in words; nothing claims a filing that did not happen'] },
  { id: 'W3b-L20-hr-throw-escapes', what: 'an HR write that throws escapes FINISH -> the screen never says what filed',
    file: 'lift-core.js',
    anchor: '      try { hrOk = (await fileHr()) === true; } catch (e) { hrOk = false; }\n',
    replacement: '      hrOk = (await fileHr()) === true;\n',
    must_fail: ['test_lift_core.mjs:L20: a Lift write that fails (or throws) is said and the HR session is still attempted'] },
  { id: 'W3b-resume-accepts-hr', what: 'an HR record is read as an open Lift session at launch',
    file: 'lift-core.js',
    anchor: '    if (input && input.store && !isOpenLift(input.store)) throw',
    replacement: '    if (false) throw',
    must_fail: ["test_lift_core.mjs:resume: the store first, then the phone; HRCore's decision and stale limit, an HR record refused as a Lift one"] },
  { id: 'W3b-pair-links-any-hr', what: 'any open HR session is resumed as the Lift session\'s own -> an unrelated recording is re-attached',
    file: 'lift-core.js',
    anchor: " && hrClaims(hr, liftSidOf(lift));\n",
    replacement: " && true;\n",
    must_fail: ['test_lift_core.mjs:resume: one RESUME for the Lift session and ITS HR session (the one naming it); an unrelated HR session keeps its own path'] },
  { id: 'W3b-guard-ignores-phone', what: 'START ignores an unfiled Lift session that only the phone holds (the 21 Sep loss, Lift side)',
    file: 'lift-core.js',
    anchor: '    var src = lift.local || lift.storeOpen;\n',
    replacement: '    var src = lift.storeOpen;\n',
    must_fail: ['test_lift_core.mjs:startGuard: START refuses over an unfiled Lift session (phone or store), then over an unfiled HR session'] },
  { id: 'W3b-Q1-archived-in-picker', what: 'an archived template stays in the picker (Q1 (a))',
    file: 'lift-core.js',
    anchor: ' && r.metadata && r.metadata.archived !== true;\n',
    replacement: ' && r.metadata;\n',
    must_fail: ['test_lift_core.mjs:templates (Q1 (a)): a record with a name and lines; archived leaves the picker, never deleted; the validator names what is wrong'] },
];

function checkRegistry(reg, discovered) {
  const problems = [];
  const discNames = new Set(discovered.map(f => basename(f)));
  const ids = new Set();
  const named = new Set();
  for (const m of reg) {
    if (ids.has(m.id)) problems.push(`${m.id}: duplicate id`);
    ids.add(m.id);
    const p = join(ROOT, m.file);
    if (!existsSync(p)) { problems.push(`${m.id}: file ${m.file} missing`); continue; }
    const src = readFileSync(p, 'utf8');
    const n = src.split(m.anchor).length - 1;
    if (n !== 1) problems.push(`${m.id}: anchor matches ${n} time(s) in ${m.file}, expected exactly 1`);
    if (m.replacement === m.anchor) problems.push(`${m.id}: replacement equals anchor`);
    if (!m.must_fail.length) problems.push(`${m.id}: names no test`);
    for (const t of m.must_fail) {
      const [file] = t.split(':');
      named.add(file);
      if (!discNames.has(file)) problems.push(`${m.id}: names ${file}, not discovered`);
    }
  }
  for (const f of discNames) if (!named.has(f)) problems.push(`suite ${f} is named by no mutation`);
  return problems;
}

function proveOne(m) {
  const problems = [];
  const p = join(ROOT, m.file);
  const pristine = readFileSync(p);
  const src = pristine.toString('utf8');
  writeFileSync(p, src.replace(m.anchor, m.replacement));
  try {
    const byFile = new Map();
    for (const t of m.must_fail) { const [file, ...rest] = t.split(':'); (byFile.get(file) || byFile.set(file, []).get(file)).push(rest.join(':')); }
    for (const [file, names] of byFile) {
      const r = runFile(join(ROOT, 'tests', file));
      if (r.ran === 0) problems.push(`${m.id}: ${file} ran ZERO tests under the mutation`);
      for (const name of names) {
        if (!r.failed.includes(name)) problems.push(`${m.id}: '${name}' did NOT fail (${file}); failed=[${r.failed.join(' | ')}]`);
      }
    }
  } finally {
    writeFileSync(p, pristine);
    if (!readFileSync(p).equals(pristine)) problems.push(`${m.id}: ${m.file} NOT restored byte-for-byte`);
  }
  return problems;
}

function main(argv) {
  const only = argv.includes('--only') ? argv[argv.indexOf('--only') + 1] : null;
  const discovered = discover();
  let problems = checkRegistry(REGISTRY, discovered);
  console.log(`prove_journal: ${REGISTRY.length} mutation(s) registered, ${discovered.length} suite(s) discovered`);
  if (argv.includes('--check')) return report(problems);
  if (!argv.includes('--skip-pristine')) {
    for (const f of discovered) { const r = runFile(f); if (r.code !== 0 || r.ran === 0) problems.push(`pristine tree NOT green: ${basename(f)} (ran=${r.ran}, failed=[${r.failed.join(' | ')}])`); }
    if (problems.length) return report(problems);
  }
  let caught = 0;
  for (const m of REGISTRY.filter(m => !only || m.id.includes(only))) {
    const pr = proveOne(m);
    console.log(`${pr.length ? 'MISSED' : 'CAUGHT'}  ${m.id}  -- ${m.what}`);
    problems.push(...pr); if (!pr.length) caught++;
  }
  console.log(`prove_journal: ${caught} CAUGHT`);
  return report(problems);
}

function report(problems) {
  console.log(`PROBLEMS: ${problems.length}`);
  for (const p of problems) console.log('  - ' + p);
  return problems.length ? 1 : 0;
}

process.exit(main(process.argv.slice(2)));
